apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
  labels:
    eks.amazonaws.com/component: coredns
    k8s-app: kube-dns
data:
  Corefile: |
    .:53 {
        errors
        health {
            lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
            pods insecure
            fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153

        hosts {
            10.233.8.243 docker-registry.tpb.vn
            fallthrough
        }

        #hosts sts.ap-southeast-1.amazonaws.com docker-registry.tpb.vn {
        #    10.233.8.205 sts.ap-southeast-1.amazonaws.com
        #    10.233.8.142 docker-registry.tpb.vn
        #}

        forward . 169.254.169.253
        # Default DNS forwarder
        forward . /etc/resolv.conf

        cache 30
        loop
        reload
        loadbalance
    }

