apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::136079915181:role/eks-node-role
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::136079915181:role/license-server-ssm-role
      username: system:node:{{SessionName}}
      groups:
        - system:masters
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system